### ISSUE TITLE
Unify the translation links

### ISSUE THREAD

**Issue by gardenBanter** [rms-support-letter/rms-support-letter.github.io#1800]
This is a mess, they should be either all text links or all flag links

![2021-03-25-121432_404x180_scrot](https://user-images.githubusercontent.com/22747136/112464396-be5d5b00-8d63-11eb-8301-9fb0776af9d3.png)

**Comment by nukeop** [comment]
Readme links are in the header, flags link to translated versions of the letter.

**Comment by gardenBanter** [comment]
I think it'd be better if you were able to access the corresponding readme from the appropriate letter translation page, which probably is the more extensible way to go. It won't be possible to fit very many links in the header once there are more translations.

**Comment by gardenBanter** [comment]
Come on, this is an eyesore!

![2021-03-25-135755_796x302_scrot](https://user-images.githubusercontent.com/22747136/112476378-1ef39480-8d72-11eb-94ad-35f27d4823ec.png)

**Comment by kitsunyan** [comment]
> Readme links are in the header

I don't think it was intentional. More seems like Jekyll included READMEs automatically, no one really asked for this.
Also the fact that translated READMEs are linked but the original one isn't doesn't make sense to me.

Since README describes repository and signing process, I'd suggested to add `README*` to `exclude` in `_config.yml`, so these pages weren't generated at all. Translated READMEs can be linked from the original one if you want.

**Comment by nukeop** [comment]
Ok, I changed it

**Comment by nukeop** [comment]
> Since README describes repository and signing process, I'd suggested to add `README*` to `exclude` in `_config.yml`, so these pages weren't generated at all. Translated READMEs can be linked from the original one if you want.

Thanks for this tip - that's what I did
