### ISSUE TITLE
The README title icon's background looks like Japanese Rising Sun Flag. I think we should replace/remove that.

### ISSUE THREAD

**Issue by shikiroot** [rms-support-letter/rms-support-letter.github.io#2634]
See here: https://en.wikipedia.org/wiki/Rising_Sun_Flag#Controversy

**Comment by nukeop** [comment]
What's wrong with it? As far as I can tell, it's just an interesting design.

**Comment by shikiroot** [comment]
> What's wrong with it? As far as I can tell, it's just an interesting design.

Maybe it's cool, but also it's very controversial.

> As the flag was used by the Imperial Japanese military during Japan's actions during World War II, it is regarded as offensive by some in East Asia, particularly in South Korea[29][30] (which was ruled by Japan) and China.[31] This symbol is often associated with Japanese imperialism in the early 20th century in these two countries.[32][33]

**Comment by dodobyte** [comment]
that's just silly, what's next? we can't use circles because it looks like japanese flag?

**Comment by shikiroot** [comment]
> that's just silly, what's next? we can't use circles because it looks like japanese flag?

Nope. I just told people it's controversial(in Asia, maybe).

**Comment by greenhorse-effect** [comment]
As a Korean, I agree that many korean will see that picture as the rising sun flag (which is said as a war crime flag).  But I don't think it should be changed for that reason, because I think the author probably indended that a halo of [St. IGNUcius](https://stallman.org/saint.html).  [Some pictures and sculptures](https://www.wga.hu/art/g/giotto/padova/5heads2/4head003.jpg) describe halo as radial shapes.  If the picture were intended as the rising sun flag, then it should be changed, because Stallman (and many other fellow contributors) would not agree with it.

And honestly, I'm little tired of calling rising sun flag anything that has radial shapes... especially in Korea.  Something that is obviously intending that flag, can give offense to many Asian country, and that should be discussed and corrected, but I don't think we should change the badge in this case.

**Comment by RealJTG** [comment]
I also thought it was a halo or nimbus.
In Soviet Russia we often refer (jokingly) to RMS as "Reverend Richard Matthew Stallman" :)

**Comment by nukeop** [comment]
I thought that flag is still in use. Honestly I've never heard it could be controversial. I'm sure @zezic intended it to be a halo, should it be changed?

**Comment by zezic** [comment]
Yeah, it was intended to be a halo, but I agree that it really looks very similar to the rising sun symbol and it can look misleading for many visitors. @nukeop, I think it's better to remove it from the repo in this case. There are many other variants for badge design, we will do something better.

**Comment by nukeop** [comment]
Ok, thanks for your comment.

**Comment by nukeop** [comment]
Removed
