### ISSUE TITLE
Repeating nickname

### ISSUE THREAD

**Issue by 6r1d** [rms-support-letter/rms-support-letter.github.io#2731]
I saw "Akram Abdeslem Chaima" twice with the same name and signature.

**Comment by shenlebantongying** [comment]
It seems she submitted twice due to the first one was invalid, but someone corrected the first one.........
https://github.com/rms-support-letter/rms-support-letter.github.io/blob/master/_data/signed/akram.yaml
https://github.com/rms-support-letter/rms-support-letter.github.io/blob/master/_data/signed/Akram.yaml

**Comment by nukeop** [comment]
I'm deduplicating signatures periodically, this will be soon automated.

**Comment by imachug** [comment]
I cleaned up the duplicates and added a script to do that to the repo.
