### ISSUE TITLE
Github is proprietary software. Why it's used to support the figher against proprietary software?

### ISSUE THREAD

**Issue by amarao** [rms-support-letter/rms-support-letter.github.io#413]
https://lists.gnu.org/archive/html/discuss-gnustep/2015-12/msg00168.html
```
GitHub does things that are quite bad for free software and is
not interested in changing them.
```

**Comment by brown121407** [comment]
It makes sense from a popularity standpoint, since GitHub is the most used software forge, it may also bring the most signatures. But I would also like if there was a way to contribute to this with free software. [SourceHut](https://sourcehut.org/) would have been a more appropriate place for this, but I don't know how much traction it would have gained then.

**Comment by nukeop** [comment]
This was in 2015. Today, Github allows you sign the letter using only free software. And it's also good for publicity.

**Comment by jdoe0000000** [comment]
Would it be possible to also allow signers to send an email to request that their signatures be added? The anti-rms repo is doing that too.

> This was in 2015. Today, Github allows you sign the letter using only free software. And it's also good for publicity.

@nukeop: I'm not aware that this is possible. Would you mind pointing out where I can find information on how to do this?

**Comment by Areso** [comment]
@jdoe0000000 
try this one:
https://docs.github.com/en/github/authenticating-to-github/signing-commits

**Comment by brown121407** [comment]
@nukeop, @jdoe0000000 

I was skeptical of the claim that you can sign the letter using only free software. I created a fork, cloned it locally, made the commit, and sent a pull request from GNU Guix's IceCat with LibreJS enabled, so I guess @nukeop was right. You *can* sign it using only free software, if "free software" includes GitHub after LibreJS blocks its non-free scripts.

**Comment by jdoe0000000** [comment]
>try this one:
>https://docs.github.com/en/github/authenticating-to-github/signing-commits

@Areso
That's for making cryptographically signed commits, not for making commits to add your signature to the support letter.

**Comment by jdoe0000000** [comment]
@brown121407 That's good to know. Thanks for finding this out!

**Comment by nukeop** [comment]
> @nukeop, @jdoe0000000
> 
> I was skeptical of the claim that you can sign the letter using only free software. I created a fork, cloned it locally, made the commit, and sent a pull request from GNU Guix's IceCat with LibreJS enabled, so I guess @nukeop was right. You _can_ sign it using only free software, if "free software" includes GitHub after LibreJS blocks its non-free scripts.

You can use Github CLI if you don't want to run non-free javascript.

**Comment by amarao** [comment]
>You can use Github CLI

Which is pure 'contrib' section for Debian, not 'main', because github cli is completely useless without proprietary server code.

**Comment by appetrosyan** [comment]
IF you are so inclined, I still have a GitLab repository. It's purely a backup, in case Microsoft decides to take this one down!

**Comment by KOLANICH** [comment]
Client code is also proprietary, and carries a browser fingerprinting script they call a "CAPTCHA".

**Comment by Motophan** [comment]
Can we try asking rms?

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
I agree with issue starter.

I am very unhappy that i _had_to_ use github account to sign this

**Comment by nukeop** [comment]
> Client code is also proprietary, and carries a browser fingerprinting script they call a "CAPTCHA". It is completely inacceptable.

Client code works with LibreJS. And you can always use the MIT-licensed github cli.

**Comment by KOLANICH** [comment]
>Client code works with LibreJS. And you can always use the MIT-licensed github cli.

Try to sign-up with your LibreJS enabled.

**Comment by ahangarha** [comment]
Just wanted express my stand with the Issue. I think those who would support RMS and FSF knew how to sign petition. I would say even number doesn't matter as much principles do. I prefer to get defeated by more people but keep my principles up.

FSF and RMS has long history of taking their (and I assume our) principles up. They don't need any compromise for getting support from their own camp, rather, it is the time to manifest the principal and ethical difference between the two camps.

I don't want to just criticize. I appreciate that unlike some sick minded people in Iran who signed petition against some Free Software activity in Iran on Facebook!!! you didn't take the petition there. I think we still can make a second option for signing the petition which is FLOSSy.

Aggregating the two list wouldn't be a big issue.

**Comment by ahangarha** [comment]
> It makes sense from a popularity standpoint, since GitHub is the most used software forge, it may also bring the most signatures. But I would also like if there was a way to contribute to this with free software. [SourceHut](https://sourcehut.org/) would have been a more appropriate place for this, but I don't know how much traction it would have gained then.

My suggestion is to make a repo there and link both to each other. Make that one the main one and let people know if it is more convenient for them to sing on github, the option is there. As the result, we won't miss anything. We both keep up with out stand for Free Software way and also give easier way to those who might have technical challenge with SourceHut.

I think it is very much practical. Then, this repo would be a mirror to that one. merge can take place every 12 hours or even daily.

**Comment by brown121407** [comment]
@ahangarha, good idea.

@nukeop please let us know what you think about this and if you're willing to cooperate on this idea. We can set up a mailing list besides a repo on Sourcehut extremely easy, and people can contribute with only free software and outside of GitHub. I volunteer to (help) manage it, apply patches and all that, if you need someone.

**Comment by nukeop** [comment]
I want a single destination for all signatures. Creating repos on other websites is a great way to spread the signatures too thinly and lose our focus. I can allow one official email address to exist, if I get access to it.

**Comment by brown121407** [comment]
@nukeop, then what about only creating a public mailing list on Sourcehut? Since it  would be public, you can read anything you want from there. We can encourage people that want to send patches created with git format-patch there or just want to request their name to be added and they don't want to use GitHub but don't know git either.

**Comment by nukeop** [comment]
If you can handle problems like spam and malicious entries, that would be perfect.

**Comment by brown121407** [comment]
@nukeop, I'll look out for spam and filter it as best as I can.

Let me know what you think about this: https://lists.sr.ht/~brown121407/rms-support-letter
The address is ~brown121407/rms-support-letter@lists.sr.ht and the details about how to work with it are in the list description.

**Comment by nataraj-hates-MS-for-stealing-github** [comment]
> I want a single destination for all signatures. Creating repos on other websites is a great way to spread the signatures too thinly and lose our focus. 

Then doing that at GitHub that is owned by most evil software corporation, is really bad idea. At least if we are speaking about __free__ software.

**Comment by brown121407** [comment]
@nukeop, we have the first signature on that mailing list I posted, so we kindly ask you to take those into consideration too. Relevant for #843 too.

**Comment by ahangarha** [comment]
I wanted to thank the person who opened this issue and those who participated in finding workaround and the maintainer who was open to suggestions and finally implemented it.

I respect such attitudes and the courage to keep up with our hold on Software Freedom.

Wish best for all.

**Comment by brown121407** [comment]
> @nukeop, we have the first signature on that mailing list I posted, so we kindly ask you to take those into consideration too. Relevant for #843 too. When you add people's signatures from there it would be kind of you to reply to their email to mention that they have been added. Thank you.

I have archived my list above so people won't send their signatures anymore, and redirected the two that signed to the list that now appears in the README. I think now this and #843 can be closed.

**Comment by Tyil** [comment]
> software forge, it may also bring the most signatures. But I would also like if there was a way to contribute to this with free software. [SourceHut](https://sourcehut.org/) would have been a more appropriate place for this, but I don't know how much traction it would have gained then.

For what it's worth, there is a copy of this repository available on Sourcehut, allowing one to completely avoid all proprietary software in order to support Stallman.

https://git.sr.ht/~tyil/rms-support

**Comment by zaytsevand** [comment]
Thanks for the opportunity to show my support in a convenient, non-discriminative for less FSF-inclined way.

**Comment by spiko-md** [comment]
Not everyone can even access github: https://developer-tech.com/news/2021/jan/08/github-restored-iran-us-gov-permits-sanctions-exemption/

**Comment by 6r1d** [comment]
@spiko-md, do you see any solutions? Should the github site be mirrored? Will codeberg and couple other ways suffice to add the signatures?

**Comment by jobbautista9** [comment]
@spiko-md The article only says that GitHub will restrict access to private repos. This one is public, so even if you're in Iran, or Cuba, you should still be able to access this repo I think.

Otherwise, there are already alternatives, like email and codeberg.

**Comment by nunojpg** [comment]
The fact that we disagree in part or almost entirely with RMS ideas (example that Github is bad for free software, sorry RMS, you are wrong), but we still understand how important he is for free software politics is what I understand one of this letter main reasons.

**Comment by KOLANICH** [comment]
>we disagree

Make statements for yourself. IMHO GH is harmful, since M$ has started abusing the power it has. I'd like to migrate off it.

**Comment by Tyil** [comment]
> example that Github is bad for free software, sorry RMS, you are wrong

RMS is right, though. GitHub may be good for open source software, but not free software. GitHub tries to persuade people to use free licenses that allow relicensing without any worry, which companies love, since it's giving them free shit with no reason to give back. But these licenses aren't viral copy-left, and thus don't guarantee any kind of freedoms to the users the moment a company decides they don't want users to have freedom.

> IMHO GH is harmful, since M$ has started abusing the power it has.

Correct, though I'd argue GitHub was a terrible platform even before Microsoft bought it.

**Comment by KOLANICH** [comment]
>open source licenses that allow relicensing without any worry

It is a good thing IMHO. Myself I use Unlicense. "Freedom" of GPL is not freedom at all

**Comment by nukeop** [comment]
Making an account somewhere is not vendor lock-in. You could argue that Github actions are a form of that, but allowing only signed in users to make comments is definitely not vendor lock-in. I have not seen a single captcha in my 5 years of using Github either.

Also FIDO/U2F is an open standard that anyone can implement and use.

**Comment by 6r1d** [comment]
> It is a good thing IMHO. Myself I use Unlicense. "Freedom" of GPL is not freedom at all, but just copyright trolling no better than the one proprietarians do.

Showing disadvantages in copyright is a morally right thing to do, not "trolling".
Many Linux modules are probably added back because of the GPL, for example.

**Comment by KOLANICH** [comment]
>Showing disadvantages in copyright is a morally right thing to do, not "trolling".

Everyone is aware about disadvantages of copyright. Some immoral people decided to play according the rules for their benefit. Some of them hypocriticaly pretend that it is a right thing and there is nothing wrong with it. BTW, there is nothing wrong with robbing people, killing people, enslaving people, extorting from people, all the people staying behind these activities in organized fashion are very well respected in every society. This is the same way nothing wrong, as using copyright.

Robbing and racketeering every businessman or just a person in some area is also "just showing disadvantages" of robbers being present in society, and according your reasoning is also a "morally right thing to do".

>Making an account somewhere is not vendor lock-in. You could argue that Github actions are a form of that, but allowing only signed in users to make comments is definitely not vendor lock-in.

GitHub Actions require (not really, it can be worked around) signin to be able to view logs and to download artifacts and to view "hidden" comments.

>I have not seen a single captcha in my 5 years of using Github either.

I have not used sign-up page since I joined GH in 2010. In December 2020 I have registered a bunch of orgs to better organize my repos. Without any "captcha". But in Jan or maybe Feb 2021 I tried to reg a few more orgs .... and saw they have introduced a browser fingerprinting script by a third party they call  a "captcha".

>Also FIDO/U2F is an open standard that anyone can implement and use.

FIDO2 spec is a backdoored standard containing "attestation". Website owners have incencetives to say people "either use FIDO2 impls that pass attestation or f*** *f" as one of the way to keep people that have negative value (wasting network bandwidth and server CPU without getting the reward they assumme they get in a form of collected "telemetry", showed ads with high enough conversion or sellig some shit) for their websites - anyone who is not a conformistic idiot.

**Comment by 6r1d** [comment]
> and according your reasoning is also a "morally right thing to do".

Wow, that escalated at a light speed!

Business benefits from Linux a lot. If it was less profitable than BSD, why is Linux popular on the servers again?
Maybe, just maybe, it's... Not that evil?

And if it is, show me your logical chain. How do you jump from GPL to robbing?

**Comment by KOLANICH** [comment]
>How do you jump from GPL to robbing?

Very easy. GPL is copyright, copyright is a tool made for de-facto robbing and racketeering people legally and copyright is actually used by people to de-facto blackmail people and de-facto extort from people, including the ones who have licensed their code under GPL (and yes, there are quite some companies whoose business model is built around extortion using GPL, often AGPL in such cases). It is completely legal, but completely inacceptable.

>Business benefits from Linux a lot.

I benefit from linux a lot. All my gadgets are linux-based. Without Linux they would have been *BSD-based. Without even *BSD they would have been Minix-based. Without even Minix, they would have been proprietary shit.

But that people benefit doesn't give anyone any right to extort, even if it is permitted by law and even enforced by law enforcement.

>If it was less profitable than BSD, why is Linux popular on the servers again?

Network effect.

>Maybe, just maybe, it's... Not that evil?

Linux itself is not evil.

**Comment by nukeop** [comment]
You're using your own definitions of "right", "robbing", "extortion" and other words, which weakens your argument. 

If you need to use emotionally charged terms to support your point it tells me that your point isn't very strong by itself. It's like you're making very decisive moral judgments about things which are typically pretty ordinary. Sounds dramatic but it's transparent that you're not too convinced yourself and need to use grandiose terminology to make your writing project more confidence than you really have.

**Comment by KOLANICH** [comment]
You have asked, I have given you the answer. What to think about my answer - it is up to you. Your beleif and approvement were not pursued.

**Comment by Motophan** [comment]
Nuke, sorry but I agree with KOLANICH.

**Comment by 6r1d** [comment]
Guys, you see, there's a bit of a problem with KOLANICH's explanation, and I feel the need to point it out.
It's nice that he's not alone, because it shows how people **miss the point** of GPL and allows me to explain why we're here to the part that isn't informed.

Now, look at this dialog:

>> Business benefits from Linux a lot.

> I benefit from linux a lot. All my gadgets are linux-based. Without Linux they would have been *BSD-based.

There it is. Do you notice this little, but interesting moment?~

> Without Linux they would have been *BSD-based

You see, the trick with GPL is that you need to **contribute back the stuff you work on**. That is, device support, drivers, kernel modules, whatever. For **gadgets**.

BSD license, sadly, does not require a manufacturer to do so. BSD having a bit less support and drivers is a direct result of that.

Yet another funny trick of modern industry is that people are **motivated by profits**. That is, if you make a screen, it's new and shiny, you really don't want to make drivers for anything but the most modern and popular, **currently proprietary** OS.

Maybe, should you be a "Screenmaker co.", you'll even pursue the BSD dev who writes drivers **in a lawsuit**, because profits are motivating you. And don't tell me that corporations are always nice and right, if some [tractor manufacturer did not pursue a farmer](https://hackaday.com/2015/05/12/ask-hackaday-fixing-your-tractor-could-land-you-behind-bars/) and [Apple were kinder](https://www.zdnet.com/article/linus-torvalds-would-like-to-use-an-m1-mac-for-linux-but/), we won't have [Right to repair](https://repair.eu/), would we now? We've got what we got, corporations want to maximize profits and it means squeezing maximum amount of money, selling your data and suing people when that's convenient.

So, nicely cutting corners and making you contribute a driver for an edge case you don't really care about (GNU GPL) is a neat tiny trick, that allows you to **have** most of your gadgets **at all** while **not working for a large corporation** with ties to screen manufacturer, sound chip manufacturer, processor manufacturer, motherboard manufacturer, video card manufacturer, whatever sensor you need manufacturer, and I can continue this list. Oh, and you can have rights for your invention, too. How cool is that?

GPL is not evil. GPL helps mankind progress outside of the large corporate sector, actually.

**Comment by Areso** [comment]
@6r1d none of your belowed gadgets will work without proprietary, closed-sorced blobs, superglued to one specific kernel. And the GPL doesn't help with the matter.

**Comment by 6r1d** [comment]
> none of your belowed gadgets

Pardon, but...
Firstly, it's "beloved" if you did not mean a pun with "below" and otherwise I miss the pun.
Secondly, I did not introduce the topic of gadgets.

> will work without proprietary, closed-sorced blobs, superglued to one specific kernel

Many of the hardware protocols are open, stuff gets more and more documented, many scopes of said blobs are limited, it's not **that terrible**, and besides, stuff like [Noveau drivers](https://nouveau.freedesktop.org/) for Nvidia is developed.

> And the GPL doesn't help with the matter.

Seriously? I think you're ignoring quite a bit of context for decades there.

**Comment by KOLANICH** [comment]
>Do you notice this little, but interesting moment?

Yes. *BSD have chosen the wrong "cathedral" model of development. Then Linux with its "bazaar" model came and have beaten BSD.

>Maybe, should you be a "Screenmaker co.", you'll even pursue the BSD dev who writes drivers in a lawsuit, because profits are motivating you.

In current legal system everyone is allowed to sue anyone (except the souvereign) no matter how nonsense the claims are. AFAIK in Common Law legal system if the defendant has failed to take part in the trial, he loses automatically. Laws disallowing RE, recreation and using of technology and distribution of information are unjust laws and must be abolished. This are the issues in the legal system, not in BSD.

>You see, the trick with GPL is that you need to contribute back the stuff you work on.

... under GPL license and even the separate products. Exactly what Steve Ballmer said. Or make a business aggreement with the copyright holder and pay him instead.

And TBH, if a company uses FOSS software, it have quite strong incentives to upstream own patches, and not only just contribute back, but make them be actually merged into the upstream. Otherwise it would be costly to maintain them. When patches are merged into the upstream, their maintainment burden is shifted to other project developers and dustributed more evenly.

Even if the software is developed by the corporation itself, it is often shared under a free license instead of a proprietary one or GPL (remember, the corp is the holder, it is not bounded with GPL terms itself, and it can relicense the software to anyone else under any license it wants (as long as permitted by law) ), to get more 3rd-party devs working on it for free. It is a kind of proof that corporations actually benefit from allowing everyone to enjoy the [4 Freedoms](https://www.gnu.org/philosophy/free-sw.en.html).

>And don't tell me that corporations are always nice and right

I have never told so.

>We've got what we got, corporations want to maximize profits and it means squeezing maximum amount of money, selling your data and suing people when that's convenient.

It is again the issue with the current legal system. It permits some kinds of de-facto racketeering and extortion and uses law enforcement to help the de-facto racketeers. It is again the issue in the current legal system. Instead of taking part in de-facto racketeering and using the fact that lot of people do that as a justification, one must change the legal system instead. There exist political parties which (at least declared) purpose is exactly that, yarr.

>Oh, and you can have rights for your invention, too.

Patents must be abolished.

> How cool is that?

Completely not cool. Copyright and patents are not rights. They are legalized racketeering and extortion.

**Comment by Tyil** [comment]
> "Freedom" of GPL is not freedom at all

A common misconception, usually brought forth from egocentrism. There's more people on the world than just you. GPL enforces freedom for the *users*, not so much the developers. If you truly care about your users, you wouldn't mind giving up the "freedom" to harm them with your software.

> In current legal system everyone is allowed to sue anyone (except the souvereign) no matter how nonsense the claims are.

More egocentrism. Please understand that not every country is as fucked as the USA. In fact, most problems plaguing that hellhole are very much localized.

> And TBH, if a company uses FOSS software, it have quite strong incentives to upstream own patches

Unless they have an advantage over the competition. In that case, unless they are *required* to upstream patches, they have a very strong (financial) incentive not to do so. See FreeBSD.

> Copyright and patents are not rights.

And that's why the GPL is called "copyleft". It fits into the same framework, but accomplishes the exact opposite, giving freedom to the users instead of taking it away for profit.

**Comment by KOLANICH** [comment]
>GPL enforces freedom for the users, not so much the developers.

Freedom is not the thing that can be "enforced".

>If you truly care about your users, you wouldn't mind giving up the "freedom" to harm them with your software.

No, taking my freedom is inacceptable. Trying to persuade me that me of freedom is necessary is like trying to persuade prisoners in concentration camps about the same. It won't be accepted.

>Please understand that not every country is as fucked as the USA. In fact, most problems plaguing that hellhole are very much localized.

No, it is the planet Earth a hellhole, US and PRC and EU and UK and RF just follow the trend.

>Unless they have an advantage over the competition. In that case, unless they are required to upstream patches, they have a very strong (financial) incentive not to do so. See FreeBSD.

If they have significant advantage in competition from that ... then they would eliminate anyone for that. Thousands and millions if necessary. No shitty license and even no court decision would stop them. Good luck in suing rich corporations (everyone knows which ones exactly, but I won't name them) with close ties to politics and significant defence contracts on the basis of their GPL violation. One suing them would be bankrupt before he even had a chance to win the lawsuit. You cannot use the tool designed specially to racketeer people against the racketeers themselves. In order to start using this tool efficiently, one has to be a racketeer and do the racket. For everything else the tool is useless. And yes, racketeers can try to racketeer racketters, so the dependence of the tool's efficiency on org power is designed to favour more poverful entities more. So the tool is inherently harmful.

**Comment by 6r1d** [comment]
> No, it is the planet Earth a hellhole
>  So the tool is inherently harmful.

Yeah, there's a lot of problems alright. So, what do you propose? What's the point you're leading us to?

**Comment by KOLANICH** [comment]
>So, what do you propose?

Not to use `[AL]?GPL-.+`.

**Comment by 6r1d** [comment]
> Not to use GPL, AGPL, GFDL and even LGPL
> Try to persuade people not to use GPL.

And what good will that bring, tactically or strategically?

And this sounds like a defeatist thinking to me, so I totally disagree.

**Comment by KOLANICH** [comment]
>And what good will that bring, tactically or strategically?

Both tactically and strategically. Less people will be relied on copyright system. Less people will pretend that copyright is good. Less people will get losses from abolishing copyright, so less of them would have incentives to vote for keeping copyright. Using GPL-like licenses will become a marker "I wanna look like a FOSSie, but wanna extort like a proprietarian" (in fact it already is, but there is large enough chance that a person was just misleaded, to determine his reall attitude to copyright one has to ask him to relicense under another license, and often the response contains clearly pro-copyright statements). It was "strategically".

Tactically: 
* if someone proposes something, he must start from himself. If one proposes abolition of copyright, he mustn't himself rely on copyright. Otherwise his words are insincere and he deserves no trust.
* more non-gpl projects means less reinvention of wheel and less fragmented ecosystem (though one can argue that a heavily fragmented ecosystem is good, it is not).

**Comment by 6r1d** [comment]
> Less people will be relied on copyright system

I believe this is shortsighted. The lack of license means you don't give others any rights to your program whatsoever in many countries. To push changes you need to show flaws in copyright to as many people as you can, especially if they have any influence and can spread the message. Which is kinda what RMS did.

> Using GPL-like licenses will become a marker "I wanna look like a FOSSie, but wanna extort like a proprietarian"

It exists for decades. We are talking about an old, widely adopted idea. Give it some credit.

> he must start from himself

Did I see unlicense in one of your repos? You can try doing that and continue that. Especially in big, popular projects. I won't agree with you completely at this point, but that's an action.

> more non-gpl projects means less reinvention of wheel and less fragmented ecosystem

Same with **more GPL projects**. More integrated stuff and more widely adopted Unix approach.

**Comment by Tyil** [comment]
Right, there's no decent discussion to be had with @KOLANICH, he just wants to be angry and pretend he's the only smart person on the entire planet. I'm out, and I'll stick to using AGPL wherever I can ;)

**Comment by KOLANICH** [comment]
>The lack of license means you don't give others any rights to your program whatsoever in many countries. 

That's why I use Unlicense.

>To push changes you need to show flaws in copyright to as many people as you can, especially if they have any influence and can spread the message. Which is kinda what RMS did.

Yes. But not by GPL, but by other activity.

>It exists for decades.

Gangs exist for decades. DPRK and PRC exist for decades.

>We are talking about an old, widely adopted idea. Give it some credit.

The fact the idea is old doesn't mean it is a good idea.

>Did I see unlicense in one of your repos? 

If you visited my GH profile (and orgs owned by me, I have moved the most of my repos into orgs because there are too much of them in the main profile) and filter out forks, you would see that most of my repos use "Unlicense" license.

>Same with more GPL projects. More integrated stuff and more widely adopted Unix approach.

No. Permissive licenses mean one is allowed to use any license he likes in own software. GPL means one must use GPL. This way GPL is a war against all other licenses.

**Comment by dzhigit1** [comment]
> No. Permissive licenses mean one is allowed to use any license he likes in own software. GPL means one must use GPL. This way GPL is a war against all other licenses.

Proprietary licenses do not allow sub licensing either. So what is wrong with GPL?

**Comment by Areso** [comment]
> Many of the hardware protocols are open, stuff gets more and more documented, many scopes of said blobs are limited, it's not **that terrible**, and besides, stuff like [Noveau drivers](https://nouveau.freedesktop.org/) for Nvidia is developed.
> 
Opensource drives are mess. I tried ones with my GTX 750 Ti, then with 1050 Ti, half of the games are failed to run/work properly. So it is working, but not very good. Not good enough. But still thanks to enthusiasts.
Any chances to run a Linux distro on a cheap laptop with Wi-Fi, bluetooth, sleep, hybernate, fingerprint scanner? Okay it was easy question, chances are good. Not 100% though.
Any chances to run a modern Linux distro with modern Kernel on a cheap tablet, which came with Windows / Android? With all the stuff, including all above, and the hardware GPU acceleration? Atom's GPUs were PITA for a decade long, may be even longer. GPUs from ARM SoCs are entirely mess.
> Seriously? I think you're ignoring quite a bit of context for decades there.
GPL doesn't (didn't) do the virus magic with those things.
And enthusiasts, well, they could choose every license they wanna use. If the first person in the chain of driver-writing select the MIT/BSD license, then it would be this. And no special-especial magic attached behind the choosing or behind the following work.
Even for big projects with a big number of contributors  GPL is not always a good choice. But for lesser projects  - I am sure the license doesn't give a hint of usefullness.

**Comment by KOLANICH** [comment]
>Proprietary licenses do not allow sub licensing either. So what is wrong with GPL?

What could be wrong with in a large part a proprietary license?

**Comment by 6r1d** [comment]
> What could be wrong with in a large part a proprietary license?

And now you're replacing "Copyleft" with "Proprietary". ;-)

**Comment by 6r1d** [comment]
> Opensource drives are mess. I tried ones with my GTX 750 Ti, then with 1050 Ti

I'm using NVidia from time to time myself. I even write this text from a computer with an NVidia video card. And I don't like the proprietary driver either. Don't waste time on arguing what sort of garbage is better, NVidia tends to mess up.

> Any chances to run a modern Linux distro with modern Kernel on a cheap tablet, which came with Windows / Android?

Reminder: I'm here to fix the situation with RMS, not to support anyone who had issues with their tablet. Yes, those are closed. And no, it's not a Linux problem. Linux will be an easier system to port there, should there be a financial incentive.

**Comment by Areso** [comment]
>  I'm here to fix the situation with RMS

Well, in that case you could stop participating in the activities, since he kinda apologized and kept his position. At least, for now.
So, the petition may be worked out as it supposed to.

> not to support anyone who had issues with their tablet.
It is how a disscussion works: starts with one subject and then, based on examples and tricks, it starts drift off somewhere else. Sometimes - entirely. Back to the tablets: I don't ask for help, I just indicated, there are 'classes' of devices, where GNU/Linux distros doesn't work properly. Why it doesn't work properly? Because GPL is not a silver bullet. Especially, with the topic. In my opinion, it is not virusable enough. You may use blobs with a kernel and it is okayish practice, acceptable by the license. So, the license is not good enough to prevent this situation happen

Finally, 
> Many of the hardware protocols are open, stuff gets more and more documented, many scopes of said blobs are limited, it's not that terrible, and besides, stuff like 

Just a cheap talk for either enthusiasts or for poors. 
Not always the documentation even exists
Not always it exists in English (there is should be a funny/sad joke about Chinese hardware makers)
Not always it is descriptive, fully enough
Not always is open and free to use without signing a deal with a Devil
Not always it is free of charge.

Let's I have (had) a printer, which was sold in dozens millions units. Canon LBP 2900, if I remember correct. The driver, should it exists, should be simple enough. Or documentation. Not compatible with GPU drivers, for a reference, in terms of complexcity.
Whatever - it was PITA to run it within popular Linux distros.
