### ISSUE TITLE
Cannot show your support without agreeing that every RMS's argument was `reasonable`

### ISSUE THREAD

**Issue by zaytsevand** [rms-support-letter/rms-support-letter.github.io#6175]
I adore efforts that were made to keep the text unbiased for the most part, but the line:
> To the ambush mob who is ganging up on Richard Stallman over reasonable arguments in debate and various opinions and beliefs voiced over decades as a public figure

implies a valuation of RMS's arguments one shouldn't be able to make without a thorough research. Which is, frankly, doesn't seem to be possible.

Also, by itself
> the ambush mob who is ganging up on

is a bit too emotionally colored as far as I'm concerned.

1st issue could be fixed by removing "reasonable" part.
2nd issue could be more of a personal taste. And I cannot raise and argument that this formula do not reflect the situation.

**Comment by 6r1d** [comment]
> implies a valuation of RMS's arguments one shouldn't be able to make without a thorough research. Which is, frankly, doesn't seem to be possible.

You can:

* Discuss what was written and said
* Generally learn more
* Analyze emotions of people mentioning stuff and their vested interests
* Use Google / DuckDuckGo / etc.
* Analyze open letter arguments one by one
* Read issues here, people did and found many refutals
* Read RMS comments, because sometimes, he actually addresses things
* Use Internet Archive to track records and changes
* Use Wikipedia logs to track edits (people did)

From that point on, you may check how credible the evidence you have is. Both for arguments for and arguments against.
And do research from there. There's nobody standing behind your back and stopping you.

> 1st issue could be fixed by removing "reasonable" part.

I have a **hypothesis**, but not more. Imagine you know someone ([Marvin](https://www.youtube.com/watch?v=EI0NXTrS5Pw)) well. And know he's old, frail, peaceful guy, who travels with his wife. You're confident and write random stuff on your mind, because you don't expect this letter. You don't do a full analysis, you don't request information from others, you don't gather evidence: you expect a bunch of people arguing over it and getting information. Your phrasing offends people and they make aggressive conclusions about you.

> is a bit too emotionally colored as far as I'm concerned.

If we were **able to** have a discussion about RMS openly and politely, none of what you see would happen.

We attempted to [establish a conversation](https://github.com/rms-support-letter/rms-support-letter.github.io/issues/175) initially and it failed, many, many times, for what it's worth.
