### ISSUE TITLE
IRC as the central point of bridges

### ISSUE THREAD

**Issue by jobbautista9** [rms-support-letter/rms-support-letter.github.io#6741]
Currently we have Matrix as our central point of bridges. However, @kompowiec proposed on #6651 that we should use IRC as the central point instead, for the following reasons:

> Well, I think it is worth combing than to divide. IRC is a good starting point for bridging the other protocols because:
> 
> * is simple protocol and easy to implemented
> 
> * works everywhere
> 
> * it's a IEFT standard
> 
> * backward compatibility - my xmpp server don't use biboumi, just something else, but still works. Meanwhile bridge with matrix to IRC break occasionally due to protocol changes

What do you guys think?

**Comment by 6r1d** [comment]
If IRC will be well moderated by us — sure thing, it can work. If it isn't as moderated, that'll be a nightmare. Changing the order of links will then be easy.

**Comment by nukeop** [comment]
Irc isn't bridged to discord or matrix. It's a bad idea, since moderation functionalities on irc lags behind other platforms.

**Comment by imachug** [comment]
It'd be possible if we had a single channel, but we have too many channels (I can name at least 7). Bridging them all to 7 different IRC channels would be a nightmare both for usage and moderation.

**Comment by nukeop** [comment]
Irc also represents lossy bridging (as you lose stuff like profile pictures). Can you even create users dynamically like on Discord? Or is it all one bot relaying all messages?

**Comment by clort81** [comment]
> Irc isn't bridged to discord or matrix. It's a bad idea, since moderation functionalities on irc lags behind other platforms.

s/moderation functionalities/retroactive deletion of posts/

fixed.

**Comment by nukeop** [comment]
That's just one of many critical functionalities for a chat platform that irc lacks.

**Comment by kompowiec** [comment]
Avatars it isn't critical features. In fact, the only thing it lacks is no chat history (especially for mobile users) At least on freenode, because it doesn't use IRCv3 afaik.

if bridge use all one bot for relaying all messages, it's nightmare and impossible to moderation, never even think about adding such a bot.

**Comment by 6r1d** [comment]
> For chat history, we can workaround this limitation by having a bot publicly logging all messages.

The question is: should we? I've been cleaning Discord from spam already, it's impossible in IRC.

**Comment by cmpunches** [comment]
I vote for IRC as well.  These other platforms are not free, not terribly standardized, some are relatively platform-dependent, and most of their clients use proprietary runtimes.

**Comment by clort81** [comment]
> That's just one of many critical functionalities for a chat platform that irc lacks.

The imposition of retroactive post censorship is critical to resist, not to implement.

**Comment by nukeop** [comment]
Please don't act needlessly dramatic. Chat moderation is completely normal and absolutely required once you have a couple hundred people in the server. With many people, you will necessarily see some that act destructively for the fun of it.

**Comment by clort81** [comment]
> Please don't act needlessly dramatic. Chat moderation is completely normal and absolutely required once you have a couple hundred people in the server. With many people, you will necessarily see some that act destructively for the fun of it.

You are avoiding the question.  IRC has been around for longer than most of you, and it was good and it still is good.

Then a bunch of corporations bigmoney funded attacks on IRC in the form of slack, discord, matrix.  Some of these corporations have ties to intelligence agencies.  The major 'innovation' they introduced was retroactive censorship of posts.

These are facts, and here you are trying to sell the idea of retroactive censorship of chats as a 'critical feature' of chat - one we did not need for over twenty years of online communities with hundreds of thousands of users.

You're the one trying to pretend this censorship tech is 'normal' when it's not.  It's a degradation and serves only the enemies that also stand on the other side of the RMS letter issue.

So tell us "nukeop", what text under 470 characters do you think must be eradicated from existence in a live chat?

**Comment by 6r1d** [comment]
> So tell us "nukeop", what text under 470 characters do you think must be eradicated from existence in a live chat?

I'm not him, but I'm a person who **retroactively deleted many, many walls** of **short** text (< 100 characters) with swearing from Discord recently. Those were done by a spam bot. **I have been deleting them manually.**. I am not sure how to do it better. Same spamming is easy enough to do with IRC, is it not? That'll be my first concern, you can ask other people in staff if you don't trust me.

> You are avoiding the question. IRC has been around for longer than most of you, and it was good and it still is good. It includes moderation such as devoicing users and banning users from channels and networks.

I'm using all of these services, because people tend to insist on each.
I honestly don't think it's a good use of RAM.
Then again, my goal is to support RMS there.

> Then a bunch of corporations bigmoney funded attacks on IRC in the form of slack, discord, matrix. Some of these corporations have ties to intelligence agencies. The major 'innovation' they introduced was retroactive censorship of posts.

I won't deny each corporation will want the control over information.
We still need to attract people from any services to show them our point **at all**.
Questions about better software on Discord aren't rare. There are helpful people, too.

> These are facts, and here you are trying to sell the idea of retroactive censorship of messages as a 'critical feature' of chat

He's not trying to "sell you an idea", he tells what he would do with a bunch off small text files pointing to each way to communicate we've got. He has a point.

> It's a degradation and serves only the enemies that also stand on the other side of the RMS letter issue.

When someone will block us, we'll just jump services. I'm paranoid about the whole thing myself, but then again, we need to attract users **first**.

**Comment by nukeop** [comment]
I told you to stop being dramatic. IRC has been growing irrelevant for years and it's not a CIA plot. It lacks basic features that hold back its popularity. The only way "big corporations" attack IRC is by making vastly superior products, to which users flock to, because they have functionalities they need (even if they suck in many ways, those you've mentioned are still way better than IRC). It's really disingenuous to defend IRC's lack of control over the channels I make as something "we didn't need for over twenty years". Apparently we did, since those chat programs ate IRC's lunch and then some. 

And there were never any "online communities with hundreds of thousands of users", because IRC channels with so many users would be full of endless, pointless spam on turbo mode. If I remember correctly, IRC at the peak of its popularity had around that number in total. Discord has 100 million, and for a very good reason. One of those reasons is that it gives you efficient tools to scale and control your community.

**Comment by cmpunches** [comment]
I won't sign onto a non-free system or service that requires javascript for this.  The only reason I'm here and not on codeberg is because I have to use github for my professional endeavours.  IRC has plenty of safegaurds against these problems that are amazingly effective.  Those shouldn't be used either except for ddos type disruptions.

**Comment by nukeop** [comment]
And btw, note that you can whine about anything all you want, as long as you're not pointlessly spamming. The stuff that needs to be deleted is a flood of gore/porn images, people who come to the chat to derail conversation on purpose, or whatever low effort trolls use these days.

**Comment by clort81** [comment]
If I may, I'd like to add a few extending comments on legitimate concerns you raised re:  moderation. 

The moderation burdens you reference are a byproduct of the design of the IRC-replacement services.  IRC by contrast is largely free of them they derive from the 'improvements' those chat models introduced, such as inline non-text media and the "bulk-send prior history to newly joining clients".

The simpler IRC model avoids the server taking 'responsibility for hosting'.  The content sent is the responsibility of the users.  Clients join channels and get new messages as they are posted.  Abusive or just generally unwelcome chatters are shown the door based on their history of behavior.  A channel or server under attack can limit access to unwelcome persons by a number of means, on a temporary or ongoing basis.

Unlike the replacement corporate chat networks, the IRC server isn't acting as a host for a full history of rich media uploaded to it.   The IRC model is that of a text-only telephone party line - the server presents a common carrier that does and can not engage in content curation and has no liability as a publisher.  The replacement model exists as a de-facto file-server which can be easily abused to host binary data, illegal porn and malware and thus becomes subject to orders of magnitude more legal liability issues. 

If you've made it this far, I thank you for your consideration.  I won't be checking responses.

**Comment by jobbautista9** [comment]
And IRC servers usually have flood protection, like Sigyn, which is a bot that automatically kicks people (from the whole network) who flood a channel, whether by accident or intentionally. You may think that this may be too harsh to users who may have accidentally posted a huge log, but this good, IMO, as it teaches them good chat etiquette. IRC clients also limit the rate of posting I think, to 1 message per second.

> Unlike the replacement corporate chat networks, the IRC server isn't acting as a host for a full history of rich media uploaded to it. The IRC model is that of a text-only telephone party line - the server presents a common carrier that does and can not engage in content curation and has no liability as a publisher. The replacement model exists as a de-facto file-server which can be easily abused to host binary data, illegal porn and malware and thus becomes subject to orders of magnitude more legal liability issues.

This one needs to be emphasized. There's no way you can upload a file to the server. You have to upload it somewhere else, then paste the link. A good example of abiding by one of the tenets of the Unix philosophy, which is "do one thing and do it well".

Now you may ask, "what about those networks which distribute illegal data via DCC?" Well, you've already answered your question. They are only uploaded and transmitted via DCC, which is merely an extension of the IRC protocol. The only connection done to the server via DCC is the handshake, which prepares the two users to communicate directly with each other. After that, the server has no liability anymore. It's like The Pirate Bay, but older.

Anyway, I think no one in the staff except me is convinced that we should move to IRC as the central point of our bridges, so I will be closing this now.
