### ISSUE TITLE
Just a curiosity

### ISSUE THREAD

**Issue by dag7dev** [rms-support-letter/rms-support-letter.github.io#7116]
Since a decision has been taken (reinstate Stallman), what's the purpose on keep merging incoming PRs?
Why is this repo still open?

Sauce: https://www.zdnet.com/article/return-of-stallman-to-fsf-sparks-outrage-among-open-source-and-free-software-leaders/
(and a bunch of other articles if you search carefully on your favorite search engine)

**Comment by nukeop** [comment]
Why would I want to delete it?

**Comment by dag7dev** [comment]
> 
> 
> Why would I want to delete it?

Never talked about "deleting it".
I clearly asked two questions.

**Comment by nukeop** [comment]
What's your point then?

**Comment by dag7dev** [comment]
> 
> 
> What's your point then?

Well, since a decision has been taken, I'm asking why is this repo still open and you / somebody else continues to merge incoming PRs. I mean, it is pointless, since a decision has been taken (and it is positive for this cause) it doesn't change anything; wouldn'it be nice to just stop to merge incoming PRs or archive this repo?

**Comment by nukeop** [comment]
It costs me nothing to keep it open and people still want to sign it.

**Comment by dag7dev** [comment]
@nukeop of course, I was just asking what's the purpose of keeping it still open.

**Comment by 6r1d** [comment]
There are people who are unhappy about the attack on Richard's personality. The method, too, because no matter how many deny the existence of the cancel culture, we hear about it all the time. There was no proof, instead it was a wave of people forcing their views on others. It even partially worked, because there were no disproven claims, no apologies, only a split of the community.

Moreover, there are people who are told not to express their opinions publicly. Otherwise, why would anyone spread the rumors about people losing jobs for expressing their opinions? For both Richard and people who feel this threat, this letter serves its purpose: reassurance and support.

As for the context, there is some:

* Lunduke on Tech: [76% Afraid of Tech Mob - Most hide true opinions](https://odysee.com/@Lunduke:e/MostAfraidOfTechMob:3)
* Lunduke on Tech: [On Mob Justice in the Tech Industry](https://odysee.com/@Lunduke:e/MobJustice:6)
